apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-volume-claim
spec:
  storageClassName: vault-gp3
  volumeName: vault-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi