apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-volume-claim
spec:
  storageClassName: ""
  volumeName: vault-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi