kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vault-gp3
provisioner: ebs.csi.aws.com 
parameters:
  type: gp3
  encrypted: 'true' 
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
mountOptions:
- debug