apiVersion: v1
kind: Pod
metadata:
  name: task-x
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.ebs.csi.aws.com/zone
            operator: In
            values:
            - us-east-1c
  volumes:
    - name: vault-pv
      persistentVolumeClaim:
        claimName: vault-volume-claim
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - name: vault-pv
          mountPath: "/var/log/"